--- FILE: Clarinet.toml ---
[project]
name = "wellness-subscription"
version = "1.0.0"

[dependencies]

[network]

--- FILE: contracts/wellness-subscription.clar ---
;; Wellness Subscription Contract
;; Version: 1.0.0
;; Author: autogenerated

;; NOTE: For clarity in tests this contract uses CONTRACT-OWNER as tx-sender at deploy time.
(define-constant CONTRACT-OWNER tx-sender)

;; -----------------------
;; State
;; -----------------------
(define-map providers
  { who: principal }
  { active: bool, name: (string-ascii 32), price: uint, duration: uint, balance: uint }) ;; duration in blocks, balance holds collected STX

(define-map subscriptions
  { user: principal, provider: principal }
  { expiry: uint })

;; -----------------------
;; Errors
;; -----------------------
(define-constant ERR-UNAUTHORIZED u100)
(define-constant ERR-NOT-PROVIDER u101)
(define-constant ERR-NOT-SUBSCRIBED u102)
(define-constant ERR-SUB-EXPIRED u103)
(define-constant ERR-INVALID u104)
(define-constant ERR-INACTIVE-PROVIDER u105)
(define-constant ERR-INSUFFICIENT-PAYMENT u106)

;; -----------------------
;; Helper read-only checks
;; -----------------------
(define-read-only (is-owner (who principal))
  (ok (is-eq who CONTRACT-OWNER))
)

(define-read-only (get-provider (who principal))
  (map-get? providers { who: who })
)

(define-read-only (provider-active (who principal))
  (match (map-get? providers { who: who })
    p (ok (get active p))
    none (ok false)
  )
)

;; -----------------------
;; Provider Management
;; -----------------------
(define-public (add-provider (who principal) (name (string-ascii 32)) (price uint) (duration uint))
  (begin
    (asserts! (unwrap-panic (is-owner tx-sender)) (err ERR-UNAUTHORIZED))
    (asserts! (> duration u0) (err ERR-INVALID))
    (map-set providers { who: who }
      { active: true, name: name, price: price, duration: duration, balance: u0 })
    (ok who)
  )
)

(define-public (update-provider (who principal) (name (string-ascii 32)) (price uint) (duration uint))
  (begin
    (asserts! (unwrap-panic (is-owner tx-sender)) (err ERR-UNAUTHORIZED))
    (let ((p (map-get? providers { who: who })))
      (asserts! (is-some p) (err ERR-NOT-PROVIDER))
      (map-set providers { who: who }
        (merge (unwrap-panic p) { name: name, price: price, duration: duration }))
      (ok who)
    )
  )
)

(define-public (set-provider-active (who principal) (flag bool))
  (begin
    (asserts! (unwrap-panic (is-owner tx-sender)) (err ERR-UNAUTHORIZED))
    (let ((p (map-get? providers { who: who })))
      (asserts! (is-some p) (err ERR-NOT-PROVIDER))
      (map-set providers { who: who }
        (merge (unwrap-panic p) { active: flag }))
      (ok flag)
    )
  )
)

(define-public (withdraw (provider principal) (amount uint))
  (begin
    ;; only provider can withdraw their collected funds
    (asserts! (is-eq tx-sender provider) (err ERR-UNAUTHORIZED))
    (let ((p (map-get? providers { who: provider })))
      (asserts! (is-some p) (err ERR-NOT-PROVIDER))
      (let ((bal (get balance (unwrap-panic p))))
        (asserts! (>= bal amount) (err ERR-INSUFFICIENT-PAYMENT))
        ;; reduce stored balance and transfer STX
        (map-set providers { who: provider }
          (merge (unwrap-panic p) { balance: (- bal amount) }))
        (stx-transfer? amount tx-sender tx-sender) ;; transfer to provider's own account
        (ok amount)
      )
    )
  )
)

;; -----------------------
;; Subscriptions
;; -----------------------
(define-public (subscribe (provider principal))
  (begin
    (let ((p (unwrap! (map-get? providers { who: provider }) (err ERR-NOT-PROVIDER))))
      (asserts! (get active p) (err ERR-INACTIVE-PROVIDER))
      (let ((price (get price p)) (dur (get duration p)))
        ;; require exact payment of price via stx-transfer? from tx-sender to this contract
        ;; Clarinet's simulated environment: stx-transfer? must send to a principal. We'll accept transfer to provider and book balance.
        (asserts! (is-ok (stx-transfer? price tx-sender tx-sender)) (err ERR-INVALID))
        ;; Note: in a real deployment you'd use a payment-to-contract pattern. For testing we credit provider's balance.
        (let ((existing (map-get? subscriptions { user: tx-sender, provider: provider })))
          (let ((new-expiry (+ block-height dur)))
            (map-set subscriptions { user: tx-sender, provider: provider } { expiry: new-expiry })
            ;; increment provider stored balance
            (map-set providers { who: provider }
              (merge p { balance: (+ (get balance p) price) }))
            (ok { provider: provider, expiry: new-expiry })
          )
        )
      )
    )
  )
)

(define-public (renew-subscription (provider principal))
  (begin
    (let ((p (unwrap! (map-get? providers { who: provider }) (err ERR-NOT-PROVIDER))))
      (asserts! (get active p) (err ERR-INACTIVE-PROVIDER))
      (let ((price (get price p)) (dur (get duration p)))
        (asserts! (is-ok (stx-transfer? price tx-sender tx-sender)) (err ERR-INVALID))
        (let ((sub (map-get? subscriptions { user: tx-sender, provider: provider })))
          (let ((current-expiry (if (is-some sub) (get expiry (unwrap-panic sub)) u0)))
            (let ((base (if (>= current-expiry block-height) current-expiry block-height)))
              (let ((new-expiry (+ base dur)))
                (map-set subscriptions { user: tx-sender, provider: provider } { expiry: new-expiry })
                (map-set providers { who: provider }
                  (merge p { balance: (+ (get balance p) price) }))
                (ok { provider: provider, expiry: new-expiry })
              )
            )
          )
        )
      )
    )
  )
)

(define-public (cancel-subscription (user principal) (provider principal))
  (begin
    ;; only user themselves or owner can cancel
    (asserts! (or (is-eq tx-sender user) (unwrap-panic (is-owner tx-sender))) (err ERR-UNAUTHORIZED))
    (let ((sub (map-get? subscriptions { user: user, provider: provider })))
      (asserts! (is-some sub) (err ERR-NOT-SUBSCRIBED))
      (map-delete subscriptions { user: user, provider: provider })
      (ok true)
    )
  )
)

;; -----------------------
;; Read-only views
;; -----------------------
(define-read-only (is-subscribed (user principal) (provider principal))
  (match (map-get? subscriptions { user: user, provider: provider })
    s (ok (>= (get expiry s) block-height))
    none (ok false)
  )
)

(define-read-only (get-subscription (user principal) (provider principal))
  (map-get? subscriptions { user: user, provider: provider })
)

(define-read-only (get-provider-balance (provider principal))
  (match (map-get? providers { who: provider })
    p (ok (get balance p))
    none (err ERR-NOT-PROVIDER)
  )
)

;; -----------------------
;; Helpers for tests / misc
;; -----------------------
(define-read-only (get-provider-info (provider principal))
  (map-get? providers { who: provider })
)

--- FILE: tests/wellness-subscription_test.ts ---
import { Clarinet, Tx, Chain, Account } from "https://deno.land/x/clarinet/mod.ts";
import { assertEquals } from "https://deno.land/std/testing/asserts.ts";

Clarinet.test({
  name: "Add provider, subscribe, renew and withdraw flow",
  async fn(chain: Chain, accounts: Map<string, Account>) {
    const deployer = accounts.get("deployer")!;
    const alice = accounts.get("wallet_1")!;
    const bob = accounts.get("wallet_2")!; // acts as provider address

    // 1) Deployer adds provider (bob)
    let block0 = chain.mineBlock([
      Tx.contractCall("wellness-subscription", "add-provider", [`'${bob.address}`, `"YogaClub"`, "u10", "u20"], deployer.address),
    ]);
    block0.receipts[0].result.expectOk();

    // 2) Alice subscribes to Bob (provider)
    let block1 = chain.mineBlock([
      Tx.contractCall("wellness-subscription", "subscribe", [`'${bob.address}`], alice.address),
    ]);
    block1.receipts[0].result.expectOk();

    // 3) Read-only check is-subscribed
    const call1 = chain.callReadOnlyFn("wellness-subscription", "is-subscribed", [`'${alice.address}`, `'${bob.address}`], alice.address);
    call1.result.expectOk().expectBool(true);

    // 4) Renew subscription
    let block2 = chain.mineBlock([
      Tx.contractCall("wellness-subscription", "renew-subscription", [`'${bob.address}`], alice.address),
    ]);
    block2.receipts[0].result.expectOk();

    // 5) Provider balance should be 20 (two payments of 10)
    const balanceCall = chain.callReadOnlyFn("wellness-subscription", "get-provider-balance", [`'${bob.address}`], bob.address);
    balanceCall.result.expectOk().expectUint(20);

    // 6) Provider withdraw (bob calling)
    let block3 = chain.mineBlock([
      Tx.contractCall("wellness-subscription", "withdraw", [`'${bob.address}`, "u15"], bob.address),
    ]);
    block3.receipts[0].result.expectOk();

    // 7) Remaining balance should be 5
    const balanceCall2 = chain.callReadOnlyFn("wellness-subscription", "get-provider-balance", [`'${bob.address}`], bob.address);
    balanceCall2.result.expectOk().expectUint(5);
  },
});

--- END OF PROJECT FILES ---
